version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: geo_distance_api_1
    volumes:
      - ./:/app
      - ./app/node_modules
    ports:
      - "3000:3000"
